name: Test
on: push

jobs:
  build:
    name: Build with Node.js 14
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
  integration-test-ubuntu:
    needs: [build]
    name: Integration test Node.js ${{ matrix.node-version }} on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['10', '12', '14']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run coverage:integration
      - uses: codecov/codecov-action@v1
  integration-test-macos:
    needs: [build]
    name: Integration test Node.js 14 on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run coverage:integration
      - uses: codecov/codecov-action@v1
  integration-test-windows:
    needs: [build]
    name: Integration test Node.js 14 on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: npm ci
      # NOTE: Cannot run with nyc in Windows.
      - run: npm run test:integration
  trigger-release:
    name: Trigger release workflow
    runs-on: ubuntu-latest
    needs:
      - integration-test-ubuntu
      - integration-test-macos
      - integration-test-windows
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Release
          token: ${{ secrets.PAT_WORKFLOW }}
